### ISSUE TITLE
Taxable salary is not working well.

### ISSUE THREAD

**Issue by fonstack** [franciscobmacedo/remotefreelancept#10]
The taxable salary will depend on your expenses. You are not taking that into account. Only 75% of the income is taxable.

**Comment by franciscobmacedo** [comment]
I am taking that into account, in the getters:

```javascript
taxableIncome() {
      if (this.rnh) {
        return this.grossIncome.year;
      }
      const grossIncome = this.grossIncome.year;
      if (this.hasExpenses || this.expensesNeeded <= 0) {
        const expensesMissing =
          this.expensesNeeded > this.expenses
            ? this.expensesNeeded - this.expenses
            : 0;
        return grossIncome * 0.75 + expensesMissing;
      }
      return grossIncome * 0.9;
    }
```

but it might no be covering all the scenarios. Can you give me an example where you found it was not working properly?

**Comment by nsenica** [comment]
I might be wrong, but I believe that for NHR situation, only 75% of the income is taxed, not 100%, and it also depends on the CAE/CIRS of the primary activity.

**Comment by franciscobmacedo** [comment]
I think you are right. I will fix the 75% issue. However to add the  CAE/CIRS situation, that's a new feature, which will require more time. 

If someone wants to do it, go for it!

- [ ] fix NHR taxable income
- [ ] Add NHR variation depending on CAE/CIRS of the primary activity.

**Comment by franciscobmacedo** [comment]
I'll close this issue and create a new one for the CAE/CIRS
