### ISSUE TITLE
pass simulation parameters through URL parameters

### ISSUE THREAD

**Issue by franciscobmacedo** [franciscobmacedo/remotefreelancept#32]
Currently the tool can simulate multiple scenarios. It would be useful that those could be shared. I propose we add a way of passing those through URL parameters. For example:

https://freelancept.fmacedo.com?income=50000&incomeFrequency=year&currentTaxRankYear=2023&...

This would then fill the corresponding values in the store and therefore render the tool with this choices.

**Comment by luisrondow** [comment]
can you assign me for this one @franciscobmacedo ?

**Comment by franciscobmacedo** [comment]
I'm sorry, I forgot to assign this to myself, as I did progress on this.
