### ISSUE TITLE
15% de despesas afetas a atividade

### ISSUE THREAD

**Issue by bolt12** [franciscobmacedo/remotefreelancept#4]
Em relação as pessoas que teem de justificar 15% de despesas afetas a atividade, mesmo que uma pessoa só consiga justificar 5%, apenas a diferença que faltar justificar será acrescido ao rendimento tributável (https://www.montepio.org/ei/pessoal/impostos/regime-simplificado-como-funciona-a-justificacao-de-despesas/). Penso que seria interessante para o utilizador poder definir uma aproximação da percentagem de despesas afetas a atividade em vez de ser binário 😄 

Ótimo trabalho! Aprendi bastante!

**Comment by franciscobmacedo** [comment]
Desculpa o atraso, mas na verdade não peguei mais nesta ferramenta. Vou fazer um upgrade para Vue3 e deixar de usar o vuetify, visto que é desnecessariamente pesado. Nesse refactoring, vou acrescentar isto também, permitindo uma selecção de percentagem entre 1 e 5%.

**Comment by bolt12** [comment]
Obrigado por responderes, e por teres implementado isto 😊
