### ISSUE TITLE
"How much can you justify as professional related expenses?" keeps changing 

### ISSUE THREAD

**Issue by tcarreira** [franciscobmacedo/remotefreelancept#42]
(This project is very well done. Congrats!)

### Description
The value on "How much can you justify as professional related expenses?" Changes automatically if I modify the income.
I think it would be nicer to keep that value if it was manually changed by me.

### Use case:

I want to fix that value (eg: to 0€) and experiment different scenarios with different income values.

### Suggestion

If the expenses value is manually changed, do not change it automatically. 
Also add a "reset" (⟲ | refresh) button right next to it, in order to go back to the current behavior.

### Open to make changes
If you think this is a useful feature, I could try to implement and create a PR. but only if you think that is useful.

**Comment by franciscobmacedo** [comment]
Great point, sounds good to me! I would suggest naming the button to "automatic" or something similar instead of reset, since the current behaviour is to set this value automatic.

Feel free to create a PR!
