### ISSUE TITLE
Cálculo de SS não coincide com a realidade

### ISSUE THREAD

**Issue by pedrosimao** [franciscobmacedo/remotefreelancept#44]
Acabo de fazer a minha primeira declaração trimestral de SS e o cálculo final foi diferente do resultado desse app.
O cálculo da SS é bem simples:

Valor Bruto * 0.7 ( 70% para prestação de serviços) * 1 à 0.75 (0% - 25% de ajuste) * 0.214 (21.4% Taxa para trabalhadores independentes)

Não sei porque, mas o cálculo do app não coincide com este.

**Comment by franciscobmacedo** [comment]
É dificil de saber o que está errado sem valores, testei agora um caso real e deu o resultado certo...

**Comment by pedrosimao** [comment]
@franciscobmacedo sim, agora me parece correto.
Só fico aqui me perguntando se o ajuste de contribuição -25% até +25% não se aplica aqueles que faturam alem do limite de 12*IAS. O que me parece é que aqueles que faturam muito, continuam pagando a contribuição máxima de 1307.78 euros atualmente, mesmo se optarem por um ajuste (para mais ou para menos).

**Comment by pedrosimao** [comment]
Sim... é realmente o que o simulador faz. Ou seja, se alguém faturar 25% a mais do que 12*IAS não se beneficia em nada ao pedir o ajuste de -25%. Acho que podemos fechar esse issue aqui!
Obrigado pela atenção!
