### ISSUE TITLE
RNH ( - Seguridade Social ) for RV

### ISSUE THREAD

**Issue by rubenmarcus** [franciscobmacedo/remotefreelancept#5]
if the person is adept of the RNH (20%) , and in the first year is Recibo Verde, theres no need for Seguridade social

**Comment by jpmoura** [comment]
That will be great if we can set a Residente Não Habitual (RNH) option, which limits the IRS to 20% and another option to set if it is his/her first year, so social security tax could be ignored

**Comment by franciscobmacedo** [comment]
Sorry for the delay, but i haven't been working on this for a while. I'll upgrade the tool to use Vue3 and will add will add both of those options.

**Comment by franciscobmacedo** [comment]
I've fixed the possibility to set  first year of activity, so that SS is 0. However, I can't seem to find reliable information on RNH - should the IRS be 20% on top of the taxable income or on top of the total gross income?

**Comment by franciscobmacedo** [comment]
solved!
