### ISSUE TITLE
Add first and second year discounts

### ISSUE THREAD

**Issue by fonstack** [franciscobmacedo/remotefreelancept#9]
Please add the possibility to select the first two years with discounts. First year is 50% and second year is 25% (in IRS)

**Comment by franciscobmacedo** [comment]
I will leave it open for when I have time or if someone wants to contribute. Here's some information about the current status of this discounts (it's not 25% in the second year, it's 40%, and there's more to it in the following years):

https://www.montepio.org/ei/pessoal/impostos/irs-jovem-como-ter-um-desconto-no-imposto/

**Comment by fonstack** [comment]
“IRS Jovem” is another thing. 

If on the year you are starting to be a freelancer, you didn’t had incomes from A or H categories you have discounts of 50% and 25% on the first and second year.

“No caso dos rendimentos associados aos coeficientes 0,75, 0,35 e 0,10, o trabalhador independente tem direito a uma bonificação de 50% e 25% no primeiro e segundo anos de atividade, respetivamente, caso estes rendimentos não sejam cumulados com rendimentos da categoria A (trabalho por conta de outrem) ou H (pensões).”

https://www.comparaja.pt/blog/irs-para-trabalhadores-independentes-coverflex

**Comment by franciscobmacedo** [comment]
ah ok, thanks for the source! Might be also interesting to adress both then. For the one that takes this issue:

- [ ] add 1st and 2nd year discount [source](https://www.comparaja.pt/blog/irs-para-trabalhadores-independentes-coverflex);
- [ ] add "IRS jovem" [source](https://www.montepio.org/ei/pessoal/impostos/irs-jovem-como-ter-um-desconto-no-imposto/)

**Comment by pedrosimao** [comment]
This one is highly needed!

**Comment by pedrosimao** [comment]
I have created this PR:
https://github.com/franciscobmacedo/remotefreelancept/pull/15

**Comment by franciscobmacedo** [comment]
Closing this issue - I'll create a new one for "IRS Jovem"
